Repository lotteon2/lotdiz-notification-service, pull requests merged in 2023-10, with the labels that each got.

#4 add: add notification entity
  src/main/java/com/lotdiz/notificationservice/NotificationServiceApplication.java
  src/main/java/com/lotdiz/notificationservice/entity/MemberNotification.java
  src/main/java/com/lotdiz/notificationservice/entity/Notification.java
  src/main/java/com/lotdiz/notificationservice/entity/common/BaseEntity.java
  src/main/java/com/lotdiz/notificationservice/entity/id/MemberNotificationId.java
  src/main/java/com/lotdiz/notificationservice/repository/NotificationRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/lotdiz/notification/entity/MemberNotificationTest.java
  src/test/java/com/lotdiz/notification/entity/NotificationTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: help wanted

#15 feat: add sqs config
  build.gradle
  src/main/java/com/lotdiz/notificationservice/config/AWSSqsConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: documentation, enhancement

#19 feat: get notification detail
  src/main/java/com/lotdiz/notificationservice/controller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/CreateProjectDueDateNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/CreateProjectFundingRateFailNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/response/GetNotificationDetailResponseDto.java
  src/main/java/com/lotdiz/notificationservice/entity/MemberNotification.java
  src/main/java/com/lotdiz/notificationservice/entity/Notification.java
  src/main/java/com/lotdiz/notificationservice/entity/common/BaseEntity.java
  src/main/java/com/lotdiz/notificationservice/entity/id/MemberNotificationId.java
  src/main/java/com/lotdiz/notificationservice/exceptionhandler/NotificationRestControllerAdvice.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/ProjectDueDateSqsListener.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationJdbcRepository.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationRepository.java
  src/main/java/com/lotdiz/notificationservice/service/MemberNotificationService.java
  src/main/java/com/lotdiz/notificationservice/service/NotificationService.java
  src/main/java/com/lotdiz/notificationservice/utils/ErrorResponse.java
  src/main/java/com/lotdiz/notificationservice/utils/SuccessResponse.java
  src/main/resources/application-local.yml
Labels: documentation, enhancement

#25 feat, fix: project due date notification
  src/main/java/com/lotdiz/notificationservice/controller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/CreateProjectDueDateNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/CreateProjectFundingRateFailNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/ProjectDueDateSqsListener.java
  src/main/java/com/lotdiz/notificationservice/service/NotificationService.java
Labels: enhancement

#26 remove: transport config from project to config service
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/utils/SuccessResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: documentation

#29 refactor: refactoring class file path and revise api spec
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectDueDateNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectFundingRateFailNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/ProjectDueDateSqsListener.java
  src/main/java/com/lotdiz/notificationservice/service/NotificationService.java
Labels: documentation

#33 feat: refactoring notification logic
  src/main/java/com/lotdiz/notificationservice/config/AWSSqsConfig.java
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectDueDateNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectFundingRateFailNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/response/GetNotificationResponseDto.java
  src/main/java/com/lotdiz/notificationservice/entity/MemberNotification.java
  src/main/java/com/lotdiz/notificationservice/entity/Notification.java
  src/main/java/com/lotdiz/notificationservice/entity/id/MemberNotificationId.java
  src/main/java/com/lotdiz/notificationservice/mapper/MemberNotificationCustomMapper.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationRepository.java
  src/main/java/com/lotdiz/notificationservice/service/MemberNotificationService.java
  src/main/java/com/lotdiz/notificationservice/service/NotificationService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: documentation, enhancement

#35 remove: removse unused config
  src/main/resources/application-prod.yml
Labels: documentation

#39 feat: add set notification read status api
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/request/SetNotificationReadRequestDto.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationRepository.java
  src/main/java/com/lotdiz/notificationservice/service/MemberNotificationService.java
Labels: enhancement

#36 release: 1.0.0
  .gitignore
  build.gradle
  deployment-prod.yml
  src/main/java/com/lotdiz/notificationservice/NotificationServiceApplication.java
  src/main/java/com/lotdiz/notificationservice/config/AWSSqsConfig.java
  src/main/java/com/lotdiz/notificationservice/controller/restcontroller/NotificationRestController.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectDueDateNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/CreateProjectFundingRateFailNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/DeliveryStartNotificationRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/SetNotificationReadRequestDto.java
  src/main/java/com/lotdiz/notificationservice/dto/request/TargetAmountAchievedProjectsDto.java
  src/main/java/com/lotdiz/notificationservice/dto/response/GetNotificationResponseDto.java
  src/main/java/com/lotdiz/notificationservice/entity/MemberNotification.java
  src/main/java/com/lotdiz/notificationservice/entity/Notification.java
  src/main/java/com/lotdiz/notificationservice/entity/common/BaseEntity.java
  src/main/java/com/lotdiz/notificationservice/entity/id/MemberNotificationId.java
  src/main/java/com/lotdiz/notificationservice/exceptionhandler/NotificationRestControllerAdvice.java
  src/main/java/com/lotdiz/notificationservice/mapper/MemberNotificationCustomMapper.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/AchievedTargetAmountProjectsSqsListener.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/DeliveryStartSqsListener.java
  src/main/java/com/lotdiz/notificationservice/messagequeue/ProjectDueDateSqsListener.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationJdbcRepository.java
  src/main/java/com/lotdiz/notificationservice/repository/MemberNotificationRepository.java
  src/main/java/com/lotdiz/notificationservice/repository/NotificationRepository.java
  src/main/java/com/lotdiz/notificationservice/service/AchievedTargetAmountProjectsNotificationService.java
  src/main/java/com/lotdiz/notificationservice/service/MemberNotificationService.java
  src/main/java/com/lotdiz/notificationservice/service/NotificationService.java
  src/main/java/com/lotdiz/notificationservice/service/UnreadNotificationService.java
  src/main/java/com/lotdiz/notificationservice/utils/ErrorResponse.java
  src/main/java/com/lotdiz/notificationservice/utils/SuccessResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/lotdiz/notification/repository/MemberNotificationRepositoryTest.java
  src/test/java/com/lotdiz/notification/repository/NotificationRepositoryTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: release

#40 feat: add pv and pvc
  deploy-prod.sh
  deployment-prod.yml
  pv-prod.yml
  pvc-prod.yml
  sc-prod.yml
Labels: release

#43 feat: add mysql config
  deployment-prod.yml
Labels: release

#44 chore: revise memory request
  deployment-prod.yml
Labels: release

#45 feat: add locale env
  deployment-prod.yml
Labels: release
